apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-search-config
  namespace: {{ .Release.Namespace }}
data:
  log4j.properties: |-
    # rootLogger log level may be programmatically overridden by -Dsolr.log.level
    solr.log=${solr.log.dir}
    log4j.rootLogger=INFO, file, CONSOLE
    # Console appender will be programmatically disabled when Solr is started with option -Dsolr.log.muteconsole
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout=org.apache.log4j.EnhancedPatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p (%t) [%X{collection} %X{shard} %X{replica} %X{core}] %c{1.} %m%n
    # we don't need file log since we run solr foreground(-f) on k8s
    log4j.appender.file=org.apache.log4j.varia.NullAppender
    # Adjust logging levels that should differ from root logger
    log4j.logger.org.apache.zookeeper=WARN
    log4j.logger.org.apache.hadoop=WARN
    log4j.logger.org.eclipse.jetty=WARN
    log4j.logger.org.eclipse.jetty.server.Server=INFO
    log4j.logger.org.eclipse.jetty.server.ServerConnector=INFO
    # set to INFO to enable infostream log messages
    log4j.logger.org.apache.solr.update.LoggingInfoStream=OFF
