kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-search-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: search-service
spec:
  selector:
    app: search
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8983
  type: {{ .Values.service.type }}
